### ISSUE TITLE
Add nanojson

### ISSUE THREAD

**Issue by mmastrac** [fabienrenaud/java-json-benchmark#1]
I had a request in the nanojson project to add it here (https://github.com/mmastrac/nanojson/issues/5). I will see if I can find some time to do it, but it would be great to see it alongside the other parsers and serializers.

My previous testing had shown pretty good results against Gson/Jackson, but I haven't run those benchmarks for a while.

**Comment by fabienrenaud** [comment]
I need to upgrade the libs and re-run the tests soon for some upcoming article... so I'll add your library to the benchmark too... this should be done before EOW. :)'

Apparently nanojson doesn't support datadbinding so the benchmark will only evaluate its "stream" deser/ser performance.

Usually, the best performing libraries recommend to input bytes (to deserialize) and get bytes (to serialize) to get the best performance results (at least while benchmarking) otherwise you get the overhead of building strings, or writers/readers and numerous memory+cpu operations that wouldn't happen with just byte[].
Does nanajson support and optimizes against byte arrays for its JsonParser...from() and JsonWriter...done() methods?

In general, if you have any recommendations to boost performance, please let me know (and I recommend you document those on your README too :) ).

**Comment by mmastrac** [comment]
The library does have some optimizations for streams when reading. I'll be releasing 1.2 shortly with some serialization improvements when writing to streams as well. It should be in maven central by tomorrow.

One thing to note with nanojson: it doesn't have a "stream" deserialization mode. It can deserialize a stream into an in-memory representation of the JSON, but does not have a token-based "reader" interface like the others. There's a performance impact of about 2-3x. I'll be working on implementing the more efficient reader as well, but that will probably be a few weeks out.

**Comment by fabienrenaud** [comment]
Here you go:
https://github.com/fabienrenaud/java-json-benchmark/tree/nanojson

This isn't looking very good for nanojson, so let me know if there are optimization I should do, upgrades I can use to rerun the benchmarks or anything else I might have missed.

I'll probably publish this mid November. Till then, it'll stay in the branch.

**Comment by mmastrac** [comment]
Thanks for this - I'll take a look and see what I can do. It's a good way to light a fire under myself to get this improved.

**Comment by mmastrac** [comment]
One thing I'd suggest - the return value of the writer is only for chaining (ie https://github.com/fabienrenaud/java-json-benchmark/commit/a7cc2ffafea743bfe9969349eee16edc506c91f1#diff-07a5f55cbf32f3aac4776d2bb8ef3a21R650). It may affect performance if you are re-assigning it.

I'd recommend changing lines of this pattern:

`cw = cw.value("balance", u.balance);`

to:

`cw.value("balance", u.balance);`

**Comment by fabienrenaud** [comment]
I made the change on my local machine and reran the benchmark but this doesn't improve performance (maybe the hotspot jvm removes unnecessary affectations). The results are about the same.

**Comment by mmastrac** [comment]
Oh, I see the problem - can you upgrade your gradle reference of nanojson to 1.2? 1.1 was seriously underpowered for writing.

**Comment by fabienrenaud** [comment]
1.2 is much better indeed. The new results (not pushed yet) show nanojson on par with jsonsmart for 1kb payloads.

You should update the version number on your readme ;)

I also quickly profiled nanojson's benchmark with jprofiler and found a lot of time was spent in emitStringValue():
http://www.screencast.com/t/uMT29cnX0

Maybe something to improve here...
If you want to profile it yourself, here is the command I used:

    ./bench -i 1000 -m 100 -f 1 ser --libs nanojson --size 1

which runs the serialization benchmark for nanojson only, only 1 fork (to which to attach the profiler), 1000 iterations of 100 seconds (to give some time to profile).

I updated the nanojson branch here so you could work off of that.

**Comment by zapov** [comment]
Your new branch has an issue with orgjson/stream. It doesn't do any serialization. It just populates a Map

**Comment by fabienrenaud** [comment]
@zapov Indeed. Next time I'll have to read my own chart...
Thanks for catching that. It's fixed now. And thanks for sharing on reddit :)

**Comment by fabienrenaud** [comment]
I have just published the results.
Everything is on master now.
