### ISSUE TITLE
Could you add minimal-json as well?

### ISSUE THREAD

**Issue by thjaeckle** [fabienrenaud/java-json-benchmark#10]
https://github.com/ralfstx/minimal-json has some outdated benchmarks itself which are quite good compared to other libraries (at that time).
Would be great to see it in the huge list you already added to your benchmark.

**Comment by fabienrenaud** [comment]
I have a few commit examples at the bottom of the readme showing how to add
a lib to the benchmark. It's quite easy and quick really.
Mind contributing and submitting a pull request? :)

You'll need java and mono installed.

**Comment by thjaeckle** [comment]
I would really like to. But here comes the "but": I have to trigger a process at my company which allows me to make PRs to this github project. 

Could take some time until I get to the actual PR then..

**Comment by fabienrenaud** [comment]
Why not doing it at home? The vast majority of contributions on github are done by putting in some personal time.

**Comment by fabienrenaud** [comment]
Done: https://github.com/fabienrenaud/java-json-benchmark/commit/7025df1475bab85c8a612de748b3e60104e0ea89

Results for 1kb payloads compared with jackson:


```
./bench deser --libs minimaljson,jackson --size 1

Benchmark                                              Mode  Cnt       Score       Error  Units
c.g.f.j.databind.Deserialization.jackson              thrpt   20  848679.759 ± 53316.383  ops/s
c.g.f.j.databind.Deserialization.jackson_afterburner  thrpt   20  871540.302 ± 46049.322  ops/s
c.g.f.j.stream.Deserialization.jackson                thrpt   20  853086.996 ± 61923.509  ops/s
c.g.f.j.stream.Deserialization.minimaljson            thrpt   20  409052.956 ±  9019.456  ops/s
```

```
./bench ser --libs minimaljson,jackson --size 1

Benchmark                                            Mode  Cnt        Score       Error  Units
c.g.f.j.databind.Serialization.jackson              thrpt   20  1448054.725 ± 72861.471  ops/s
c.g.f.j.databind.Serialization.jackson_afterburner  thrpt   20  1579810.000 ± 71411.435  ops/s
c.g.f.j.stream.Serialization.jackson                thrpt   20  1413661.875 ± 48743.624  ops/s
c.g.f.j.stream.Serialization.minimaljson            thrpt   20   601603.929 ± 63931.802  ops/s
```
