### ISSUE TITLE
Support more java types (UUID, enum, LocalDate...)

### ISSUE THREAD

**Issue by fabienrenaud** [fabienrenaud/java-json-benchmark#12]
From @zapov https://github.com/fabienrenaud/java-json-benchmark/issues/11

> Did you consider some more java-like types, eg UUID instead of String for the guid field, enum for the color/fruit, long instead of String for one id....?

> Ideally it would be nice to have LocalDate, OffsetDateTime in there, but that might be a problem for few libs? Those are usually performance killer in most benches.

**Comment by fabienrenaud** [comment]
The user model is written for testing simple pojos with simple data types and limited nesting. Other data types should be tested as part of a different/new model. I would even suggest to micro-benchmark performance of specific types of against others so devs can choose which is best for json.

The project supports multi-model testing. It's just that I haven't written any other models...

Pull requests are welcome of course. :)

**Comment by fabienrenaud** [comment]
Sorry for the delay. Your PR is now merged.
I will rerun the full benchmarks in this week-end or the next.

Thank you for your contribution.

**Comment by fabienrenaud** [comment]
I have just published the new results.
Please let me know of any feedback.

**Comment by zapov** [comment]
Great news.

But it seems dsljson failed for you with some NPE?
Can you provide more info about that? I can't seem to replicate that.

It wasnt failing when I submitted the PR, and it's not failing if I comment out the NPEs and remove the false on setup.

I've tested it by

    gradlew build

that passes (with removal of test overrides)

    gradlew shadowjar

and

    java -cp app.jar com.github.fabienrenaud.jjb.Cli ser --libs dsljson --datatype clients

**Comment by fabienrenaud** [comment]
Given enough tries, there are two kinds of issues I run into with dsljson:

The NPE one:
```
com.github.fabienrenaud.jjb.databind.ClientsDeserializationTest > dsljson STANDARD_OUT
    Difference in Clients!
       Original   : Clients{clients=[JsonDataObj{_id=361049024745910000, index=574557740, guid=dd115f83-4102-7869-8221-b7318fccc930, isActive=false, balance=0.3043090436535292, picture=vqML0kjE12AyxfLTbeItHKeUTAOPJVrYv0x5yeeE7jIKoh32ztwYgpboFnGKZOiTketSwr4d9DPCBjXDLxmob1RNLURFgPQzjyOj, age=87, eyeColor=BLUE, name=VkEmT4D4HXb9QdGzlvy0, gender=mS2zsfRn2gc4anExavvK, company=pW9vAhJwMtxj02uurzas, emails=[JsdTDbROXCbuRYcAcAnp, giaNWlBYwVsrnEyVUANn, DpEkXqkVoReSqKvkamdt, qcaNvzvwDMRRBMAvvDXh], phones=[484310224,904377097,726146796,2066330945,245309399], address=pUHH5yyurGrKQPyqTpDm, about=F8WN04yaQzCQ7kQscSMF, registered=1943-02-24, latitude=73.06197096080942, longitude=129.7267639294668, tags=[HepjOZEfis, lM4Dk1pzC0, 791QfWRP5A, 6D3LBSwe0y, 777Rd0EkMC, qLymyGC8Bm, L5nC33dTTP, 9D39SxrcXL, Dao0DFQS6t, VrbumAM5BO, cKBmDT6Ezg, 8QVWfUpO2t], partners=[Partner{id=-1784726995776911118, name=DnUpPKIrWCeppXnlFhRwcCuNnvGnlI, since=1991-01-15T04:25:46.461712507Z}, Partner{id=-528093366365669374, name=cLLLFbusAqZwCeFkqEakKRHcZMSvOX, since=1908-12-27T12:57:55.059093411Z}, Partner{id=626464364438776455, name=vpHZqQsopfFZIKMTrBYdRYECHJfbqf, since=1921-05-06T15:30:57.563049374Z}, Partner{id=-6463649724960336005, name=OtqiuhVFXXNEbuhJmewgQflREnDeKr, since=1996-12-13T08:57:59.381879045Z}]}, JsonDataObj{_id=8495938657654601934, index=1588429411, guid=80fa425c-524f-6320-ae74-44a8c777b65f, isActive=true, balance=0.8146454860969802, picture=Q3Lz9aHiowmZSPi6qtWiqS8o7Uk0aNWPl7Tl7zx4wefKJmeWGZR4KlRUEYxYPKOzKq7jCjTKOCvEK2RSRAcM6ot7apJ4mdFueSp7, age=30, eyeColor=BLUE, name=PB9ezc9w08RZRjTepy5c, gender=JgnHTfdwrczE78zlt018, company=kxpVLiHJdc4DPbjyA4nI, emails=[], phones=[1780718763,1021660101,1974148155,1584902032,2087897352], address=3MbxjlKwCSDez6N2fXdy, about=pKHmqVKhrsBjSzjXBVKW, registered=1931-07-03, latitude=4.427053572505657, longitude=79.14663289644633, tags=[SmB084Hxno, WL9FRzmuZf, eKVU0NJOr0, wAGUOL1H9x, 1wsDFmr6DS, 8Ec9vS5Rp7, S1xE8qXpXl, CuHUsTkkyo], partners=[Partner{id=4812374947509775416, name=MmqdFyJEZJlmwHTELSuBozMGoIpToH, since=1931-11-27T14:44:31.769224575Z}]}]}

com.github.fabienrenaud.jjb.databind.ClientsDeserializationTest > dsljson FAILED
    java.lang.NullPointerException
```

An equality error (on one of the doubles):
```
com.github.fabienrenaud.jjb.data.gen.ClientsGeneratorTest > populateClientCollection_1k STANDARD_OUT
    Using SEED=1456495961223546 as seed for Random

com.github.fabienrenaud.jjb.databind.ClientsSerializationTest > dsljson_reflection STANDARD_OUT
    Difference in Clients!
       Original   : Clients{clients=[JsonDataObj{_id=754212144305802375, index=1470994940, guid=ed22443f-0c49-6cb7-cf81-6963872f76de, isActive=true, balance=0.08338577727527452, picture=GLnAietyeuFWnzY0VNscewITCfwCtlb82nDzxUErbMWE9np30RHRsnNWheYesFxQWKHLdHTPB3VP9e9SgvAvumxqmCgcTlp5JGNf, age=89, eyeColor=BLUE, name=EdcxQtgE6v7ztq6DVFbO, gender=Df4yc1MxNotWfl0aHEA5, company=lx4ktZuBJqjDzdsjDHWr, emails=[hlaKuVHYSXiepKonsLax, qIGvQbgfuqdAGpfFSJmQ, YJqYuCrzdifneTMPoRXK], phones=[388931175,177117478,1298638345,1443807148,100933983,297143752], address=iCLJSTV4uy2eEk3bMfX6, about=yL4CWnlO7w9miQ5B6Fyd, registered=1904-01-11, latitude=79.42711861002195, longitude=21.11495338575979, tags=[2s8cdBZmE0, 48GhOwG1G6, LxxlFyuKXi, 3XlAUF3sjX, drNZeoxul2, 9ydRiWhoQa, HKxxw1nVzy, CfHMdheXvL, RFrKc7N3tw, Ds7x8wuvNG, Bdg2g8jn5f, gf5Wrnj0MD, crBefr7Gw4, GqJwJAMKVY, Qri3s7D8Ce, tDDkHUZHKJ, OubVJT2cP4, hrFqBWe9Iv, pE3RkBdkIh, Jmvx6VVHlB, MBMNNRcHzC, ZYgA97OElX, ReLPwx75sd, 1FjnsYIu0K, FP4fmzkZB8, rsmeh1PgHd, Jr77gHF79j, wXS5sf8Sja, 2IPPGFLxWR, U2SIh4YYAB, zlHSrwCk5y, hiFj77oAnm, gkyUizraNl, j2Bb40bwQY, JcbqrOYpT1, a21NTyr68J, BI1IRXC0EJ, dS57mULLBW, 22DxV0S9Rb, 1JU4JFjONr, O7DBCbOEpl, pt6Ywj7Iuy, 9M494hJcQQ], partners=[Partner{id=4376407450868779048, name=PSbjnMhFBYxPKZPNsxxBRBiFyptqoa, since=1911-01-11T13:46:01.538695822Z}, Partner{id=-1049058417240388796, name=YytIcoRFfoWQaImcjKnGsenIhPQTCk, since=1955-01-04T15:28:59.942914361Z}, Partner{id=7310933602268492048, name=CHCJBQlyGWSJKrfmLqoBEptwSDzjij, since=1948-07-24T04:51:55.129436657Z}, Partner{id=-3811453752287548559, name=IKWvgaycYVGoZaknUuZNfDbNPaKpjP, since=1930-09-18T21:24:14.081528906Z}, Partner{id=3680439123962074276, name=ILGQLlewDhHYPcYTQLvdIpwEjIGEXN, since=1909-04-18T14:55:34.147099365Z}, Partner{id=5731552886544858164, name=OQClWNqDbwsAZijaOhlDYNpwcMlUFh, since=2007-01-13T20:12:14.137383130Z}, Partner{id=-736566970085987477, name=mSnZTQeqsJJiDHpZhevpGbHioJNanf, since=1903-09-15T08:54:06.856423075Z}, Partner{id=5390750276457445990, name=HFGgZOntGYqclCsYsemDdIWMLibvkP, since=1900-11-04T08:11:14.047899612Z}, Partner{id=6095818507611336619, name=BrrtGLlGcJzPxpSUsENRwwnlhBVbvU, since=1956-09-05T16:40:03.061468387Z}]}]}
       Transformed: Clients{clients=[JsonDataObj{_id=754212144305802375, index=1470994940, guid=ed22443f-0c49-6cb7-cf81-6963872f76de, isActive=true, balance=0.08338577727527452, picture=GLnAietyeuFWnzY0VNscewITCfwCtlb82nDzxUErbMWE9np30RHRsnNWheYesFxQWKHLdHTPB3VP9e9SgvAvumxqmCgcTlp5JGNf, age=89, eyeColor=BLUE, name=EdcxQtgE6v7ztq6DVFbO, gender=Df4yc1MxNotWfl0aHEA5, company=lx4ktZuBJqjDzdsjDHWr, emails=[hlaKuVHYSXiepKonsLax, qIGvQbgfuqdAGpfFSJmQ, YJqYuCrzdifneTMPoRXK], phones=[388931175,177117478,1298638345,1443807148,100933983,297143752], address=iCLJSTV4uy2eEk3bMfX6, about=yL4CWnlO7w9miQ5B6Fyd, registered=1904-01-11, latitude=79.42711861002195, longitude=21.11495338575979, tags=[2s8cdBZmE0, 48GhOwG1G6, LxxlFyuKXi, 3XlAUF3sjX, drNZeoxul2, 9ydRiWhoQa, HKxxw1nVzy, CfHMdheXvL, RFrKc7N3tw, Ds7x8wuvNG, Bdg2g8jn5f, gf5Wrnj0MD, crBefr7Gw4, GqJwJAMKVY, Qri3s7D8Ce, tDDkHUZHKJ, OubVJT2cP4, hrFqBWe9Iv, pE3RkBdkIh, Jmvx6VVHlB, MBMNNRcHzC, ZYgA97OElX, ReLPwx75sd, 1FjnsYIu0K, FP4fmzkZB8, rsmeh1PgHd, Jr77gHF79j, wXS5sf8Sja, 2IPPGFLxWR, U2SIh4YYAB, zlHSrwCk5y, hiFj77oAnm, gkyUizraNl, j2Bb40bwQY, JcbqrOYpT1, a21NTyr68J, BI1IRXC0EJ, dS57mULLBW, 22DxV0S9Rb, 1JU4JFjONr, O7DBCbOEpl, pt6Ywj7Iuy, 9M494hJcQQ], partners=[Partner{id=4376407450868779048, name=PSbjnMhFBYxPKZPNsxxBRBiFyptqoa, since=1911-01-11T13:46:01.538695820Z}, Partner{id=-1049058417240388796, name=YytIcoRFfoWQaImcjKnGsenIhPQTCk, since=1955-01-04T15:28:59.942914360Z}, Partner{id=7310933602268492048, name=CHCJBQlyGWSJKrfmLqoBEptwSDzjij, since=1948-07-24T04:51:55.129436650Z}, Partner{id=-3811453752287548559, name=IKWvgaycYVGoZaknUuZNfDbNPaKpjP, since=1930-09-18T21:24:14.081528900Z}, Partner{id=3680439123962074276, name=ILGQLlewDhHYPcYTQLvdIpwEjIGEXN, since=1909-04-18T14:55:34.147099360Z}, Partner{id=5731552886544858164, name=OQClWNqDbwsAZijaOhlDYNpwcMlUFh, since=2007-01-13T20:12:14.137383130Z}, Partner{id=-736566970085987477, name=mSnZTQeqsJJiDHpZhevpGbHioJNanf, since=1903-09-15T08:54:06.856423070Z}, Partner{id=5390750276457445990, name=HFGgZOntGYqclCsYsemDdIWMLibvkP, since=1900-11-04T08:11:14.047899610Z}, Partner{id=6095818507611336619, name=BrrtGLlGcJzPxpSUsENRwwnlhBVbvU, since=1956-09-05T16:40:03.061468380Z}]}]}


com.github.fabienrenaud.jjb.databind.ClientsSerializationTest > dsljson_reflection FAILED
    java.lang.AssertionError
```

The NPE isn't 100% repro but I remember getting it very frequently a week or 2 ago. As you can see, I'm not getting any stacktraces with the null pointer exception. The issue may or may not depend on the seed, so printing its value may help.

To run the tests over and over: `./gradlew clean build`

**Comment by zapov** [comment]
I actually managed to reproduce the issue... but it got even more weirder from there ;(

So the first issue I traced down to email=[] in original and email=null in dsljson.... which doesn't really make sense... but I'll add more logging to see whats going on.

The second issue is not actually a problem with doubles, but with java time!? which gets last digit zeroed out!? (1956-09-05T16:40:03.061468387Z vs 1956-09-05T16:40:03.061468380Z)

But if I try to parse this exact value in dsljson then it works as expected ;(

I'll look into it some more, but I'm not convinced that dsljson is the problem here ;(

**Comment by fabienrenaud** [comment]
> I've fixed the NPE in external compiler

What do you mean by "external compiler"? There was an issue in the .net annotation processor?

> Ideally external compiler should not be used since v1.7.1 but I'll look into removing that and just using plain Java later

It would be nice to have that before running all the benchmarks again :)

> The second issue is not actually a problem with doubles, but with java time!? which gets last digit zeroed out!?

Indeed. It might be jackson (which is the de facto lib used for all verifications in tests) dropping the last digit...

**Comment by zapov** [comment]
Yes, .NET annotation processor uses compiler which it downloads locally unless configured differently (thats the DSL Platform compiler).

Last time I checked they (.NET vs Java8) had the similar performance (which you can check by commenting out .NET annotation processor and uncommenting the Java8 one.
There are still some optimizations missing, but not sure if it's visible in this benchmark.

I'm still looking into this java time issue but it seems to happen quite rarely.

I suggest running the benchmark as is in this PR if thats ok with you

**Comment by zapov** [comment]
Yes, you are right. Jackson sometimes omits the last digit in datetime which causes failed comparison with DSL-JSON which does not. That error message for transformed was throwing me off, since I was assuming that transformed is the DSL-JSON, while it was Jackson.

**Comment by fabienrenaud** [comment]
Alright. I’ll merge in your PR and try to rerun all this in the next couple
of weeks. I will probably try to switch DSLjson to the java annotation
processor though to reflect best the performance of v1.7.1. It would help
if you could do that part but don’t feel like you have to...

**Comment by zapov** [comment]
I'll release the 1.7.2 this week and if you wish upgrade that PR with it (and remove .NET version).

**Comment by fabienrenaud** [comment]
Sounds good.
