### ISSUE TITLE
Add FST (fast-serialization)

### ISSUE THREAD

**Issue by SebAlbert** [fabienrenaud/java-json-benchmark#13]
Is [this library](https://github.com/RuedigerMoeller/fast-serialization) a candidate for participation in this benchmark?

I would like to see an independent result for the promising performance seen in [their own benchmark](https://ruedigermoeller.github.io/fast-serialization/json_bench.html).

**Comment by zapov** [comment]
Thats a binary serialization.
You have independent results at: https://github.com/eishay/jvm-serializers/wiki

**Comment by fabienrenaud** [comment]
Apparently, fast-serialization does provide a [json serializer backed by jackson-core](https://github.com/RuedigerMoeller/fast-serialization/wiki/JSON-serialization) so it could be added to the project but their json benchmark actually shows worse performance for FST json over jackson serialization. The better perf is for the "FST unshared" which probably serializes to binary (and that's out-of-scope for this project as zapov said).

As long as it's serializing and/or deserializing json, pull requests are welcome :)

**Comment by SebAlbert** [comment]
I see. I was mislead by the idea that their entire benchmark was about JSON (cf. the filename), but after re-reading the page @fabienrenaud mentioned, I understand that the fast results for fst "unshared" are rather for comparison and do not produce JSON.
