### ISSUE TITLE
Add Moshi

### ISSUE THREAD

**Issue by Kisty** [fabienrenaud/java-json-benchmark#2]
Why not add [Moshi](https://github.com/square/moshi)?

**Comment by fabienrenaud** [comment]
Done! (here: https://github.com/fabienrenaud/java-json-benchmark/commit/d8d9b93a74a72f5bb6597fda852482ff15597300)

I did a quick run against jackson (1kb payload):


    ./bench ser --libs jackson,moshi

    Benchmark                                            Mode  Cnt        Score        Error  Units
    c.g.f.j.databind.Serialization.jackson              thrpt   10  1425517.770 ± 169599.650  ops/s
    c.g.f.j.databind.Serialization.jackson_afterburner  thrpt   10  1423991.580 ±  74626.812  ops/s
    c.g.f.j.databind.Serialization.moshi                thrpt   10   573666.442 ±  54966.743  ops/s
    c.g.f.j.stream.Serialization.jackson                thrpt   10  1355165.959 ±  76052.994  ops/s

moshi serialization performs similarly to johnson (in reference to the graphs on the home page).

    /bench deser --libs jackson,moshi

    Benchmark                                              Mode  Cnt       Score       Error  Units
    c.g.f.j.databind.Deserialization.jackson              thrpt   10  804436.221 ± 69957.322  ops/s
    c.g.f.j.databind.Deserialization.jackson_afterburner  thrpt   10  835109.655 ± 78512.781  ops/s
    c.g.f.j.databind.Deserialization.moshi                thrpt   10  390417.721 ± 44489.799  ops/s
    c.g.f.j.stream.Deserialization.jackson                thrpt   10  804249.671 ± 54846.021  ops/s

moshi deserialization performs similarly to boon (in reference to the graphs on the home page).

For now, my moshi code is serializing from/to strings... using moshi's JsonWriter/JsonReader didn't seem super trivial so the benchmark above also counts time it takes to build the read/write buffers, which degrades measured performance. I'll try to improve that some time later this week.

Let me know if you can think of any performance improvements I can do for moshi.

**Comment by Kisty** [comment]
Nice one! Thanks for that and such quick response and work! Thank you!

I'm not too familiar with Moshi, but have heard about it from @JakeWharton's [talk](https://www.youtube.com/watch?v=WvyScM_S88c) about their low-level java io library, [Okio](https://github.com/square/okio/).

@JakeWharton, any ideas what else could be done to further improve the benchmark?

Am currently on Windows 10 so not sure how I'd run benchmarks. Perhaps I could use the Linux subsystem on Windows...

**Comment by fabienrenaud** [comment]
What I meant is if I missed some best practices rules that aren't documented properly or a way I can use (not change) the moshi lib to get more perf out of it, and if you know it, then I'm all ears :)
For example, jackson has a wiki page about best practices and what to do to not ruin performance:
https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#basics-things-you-should-do-anyway

So you shouldn't need to run the benchmark at all to figure that out unless you are actively working on improving moshi/one-of-the-json-libs.

But, if you want to run ./bench on Windows, all you got to do is run 1 gradle and 1 java command from the console and those work on windows. The script is really simple:
https://github.com/fabienrenaud/java-json-benchmark/blob/master/bench

    cd to/the/dir/of/java-json-benchmark
    gradle shadowJar
    java -server -XX:+AggressiveOpts -Xms2G -Xmx2G -cp build/libs/benchmarks*.jar com.github.fabienrenaud.jjb.Cli <options>

**Comment by JakeWharton** [comment]
Moshi is comparable to Gson, not Jackson. We have no intention of trying to go after Jackson which has to be 50x larger in library/code size to achieve such speed.

Additionally, it looks like the benchmarks only take into account deserializing from a `String` which is also not an optimal path though the library. The string has to first be encoded to UTF-8 only to have all its string values be decoded from UTF-8 back into strings. This is very uncharacteristic of how the library would normally be used.

Moshi shines when you're doing two things: dealing with bytes and also dealing with Okio's types. For example, if you give it an `okio.Buffer` as the source of data it will incur no overhead that you'd otherwise see when using a `String`.

cc @swankjesse

**Comment by fabienrenaud** [comment]
I'm planning on polishing this to use the buffers from okio.
But since I am unfamiliar with that API and moshi's readme doesn't directly show how I could use it, then I didn't do in the fist implementation (which I did very quickly).
moshio also doesn't provide a high level method to deserialize to/from bytes so I'll need to find out how to use Okio.

**Comment by JakeWharton** [comment]
Yes, you're forced to use okio.Buffer (as a BufferedSource or BufferedSink)
which can eat or produce byte[]s.

**Comment by fabienrenaud** [comment]
Alright. The code is now using Okio buffers.
I even wrote a custom ReusableSource that doesn't close the InputStream such as I could reuse input streams for moshi, just like I do for other jackson and other libs.

I ran the benchmark against moshi,gson and jackson for 10KB payloads this time.


Deserialization results:

    ./bench deser --libs jackson,moshi,gson --size 10

    Benchmark                                              Mode  Cnt      Score       Error  Units
    c.g.f.j.databind.Deserialization.moshi                thrpt   10  47742.876 ±  5422.307  ops/s
    c.g.f.j.databind.Deserialization.gson                 thrpt   10  50080.862 ±  5726.813  ops/s
    c.g.f.j.databind.Deserialization.jackson              thrpt   10  73811.604 ± 10556.266  ops/s
    c.g.f.j.databind.Deserialization.jackson_afterburner  thrpt   10  85430.561 ± 12801.308  ops/s

Serialization results:

    ./bench ser --libs jackson,moshi,gson --size 10

    Benchmark                                            Mode  Cnt       Score       Error  Units
    c.g.f.j.databind.Serialization.gson                 thrpt   10   50700.741 ±  7404.496  ops/s
    c.g.f.j.databind.Serialization.moshi                thrpt   10   64010.218 ±  2741.320  ops/s
    c.g.f.j.databind.Serialization.jackson_afterburner  thrpt   10  132777.690 ± 15012.412  ops/s
    c.g.f.j.databind.Serialization.jackson              thrpt   10  140693.532 ±  6357.017  ops/s

**Comment by fabienrenaud** [comment]
On master.
Closing.
