### ISSUE TITLE
Add mjson results

### ISSUE THREAD

**Issue by gmacd** [fabienrenaud/java-json-benchmark#22]
This looks great - are the mjson results available?

Thanks!
Graham

**Comment by fabienrenaud** [comment]
Considering how poor the performance of mjson was, I didn’t want to go
through a full benchmarking round just for that lib...
Meanwhile, you can find results at the end of issue #21 and it is always
easy to run a few tests locally :)

**Comment by gmacd** [comment]
Thanks, that's the information I was looking for :)
