### ISSUE TITLE
Please add underscore-java library

### ISSUE THREAD

**Issue by javadev** [fabienrenaud/java-json-benchmark#24]
Hi,

Please add underscore-java library to the list.

Kind regards, Valentyn

**Comment by fabienrenaud** [comment]
Hello, pull requests are welcome. :)
There are many single commit examples showing how easy it is to add a lib to the benchmark suite: https://github.com/fabienrenaud/java-json-benchmark#contribute

**Comment by javadev** [comment]
Hi,

I prepared pull request: https://github.com/fabienrenaud/java-json-benchmark/pull/25

Kind regards, Valentyn

**Comment by fabienrenaud** [comment]
Resolved by https://github.com/fabienrenaud/java-json-benchmark/pull/25
