### ISSUE TITLE
add Exclude file with FIM application ? 

### ISSUE THREAD

**Issue by CMA-CGM** [fabienrenaud/java-json-benchmark#26]
Hello,

I'm on project to use FIM application to monitor TRAX/TSG application (FIS editor who recommend your product)

Currently our tests are compliant with our security team.

But I'm meet problem to add excluded path, because i'm oblige to put FIM at root folder but I should exclude some folder inside ( log folders, temp folders). and I don't find the command for that ...

Any idea ?

My mail: ext.epiveteau@cma-cgm.com

**Comment by fabienrenaud** [comment]
Hello,
Please clarify how this request has anything to do with this project (a benchmark).

**Comment by CMA-CGM** [comment]
Good Morning Fabien,


This is ours Project:

CMA-CGM (our client) use TSG Application (FIS company). To be compliant with new security SWIFT order, we oblige to secure our transaction payment via TSG Application.

FIS editor asks to us to install your solution FIM to realize a daily check of our Application TSG; if there is any modification of files or folders. They recommend to us to use your solution FIM. I deploy your solution with success.

My request is to understand how I can add some Excluded path into FIM analysis? Because, I don’t see any information into your documentation (See file joint)

Thank you for your help…




Cordialement, Best regards
_______________________________________
Emmanuel PIVETEAU
Service Integration -  BT Finance
IBM  for CMA CGM
OFFICE IBM Tél. : +33(0) 4 96 20 45 00

**Comment by fabienrenaud** [comment]
1. Please define all acronyms.
2. You can't attach files to github issues.
3. This project has nothing to do with FIM, TSG and it not meant to be integrated with anything so you are most likely on the wrong track.

**Comment by CMA-CGM** [comment]
Dear Fabien,

I send to you the recommendation documentation from TSG editor who put your application has reference to realize a full item control.


Also, Can you please tell me how send request to FIM support?
Because I don’t find anything into your site. Or maybe you’re not the right person to contact?





Cordialement, Best regards
_______________________________________
Emmanuel PIVETEAU
Service Integration -  BT Finance
IBM  for CMA CGM
OFFICE IBM Tél. : +33(0) 4 96 20 45 00

**Comment by fabienrenaud** [comment]
Like I said: attachment don't get through and this project has nothing to do with FIM, TSG or any other acronym I've never heard of before.

> Can you please tell me how send request to FIM support?
How would I know how to contact something you are using and I've never heard of before?
