### ISSUE TITLE
Dependency (Jackson 2.10) and JDK upgrade

### ISSUE THREAD

**Issue by chrisgleissner** [fabienrenaud/java-json-benchmark#30]
Hi @fabienrenaud,

Thanks for this excellent benchmark! 

Since you last ran it, Jackson 2.10.1 got released and a lot of projects have moved to OpenJDK 11. I reran the benchmark for a small subset (Jackson and Yasson) of the overall measurements on my laptop and published the results in a fork of your project, but it would be great if we could return the entire set.

Would you be interested in a merge request updating all the frameworks to the latest published versions and also making sure it runs under JDK 11, or have you already started work on this yourself?

Thanks

**Comment by fabienrenaud** [comment]
Sounds good. Contribution is welcome :)

**Comment by fabienrenaud** [comment]
Done. Tests took 12 hours (or so) to run.

**Comment by chrisgleissner** [comment]
Thank you very much!
