### ISSUE TITLE
include stream vs databind in graphs?

### ISSUE THREAD

**Issue by joshwand** [fabienrenaud/java-json-benchmark#31]
It'd be good to be able to view the performance of stream vs databind in the presented graphs, so viewers like me can see which implementation to choose for performance.

**Comment by fabienrenaud** [comment]
Graphs are too dense already.
For finer details such as this, you can always look at the raw results (linked on the readme):
https://github.com/fabienrenaud/java-json-benchmark/blob/master/archive/raw-results-2020-03-01.md
