### ISSUE TITLE
CLI example commands throw ParseArgumentsUnexpectedException

### ISSUE THREAD

**Issue by langelescu** [fabienrenaud/java-json-benchmark#39]
**$> ./run deser --apis stream --libs genson,jackson**
.\gradlew clean build shadowJar

> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileTestJava
Note: C:\Users\lange\dev\projects\external-workspaces\java-json-benchmark\src\test\java\com\github\fabienrenaud\jjb\JsonBenchmark.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

com.github.fabienrenaud.jjb.data.gen.ClientsGeneratorTest > populateClientCollection_1k STANDARD_OUT
    Using SEED=793328287 as seed for Random

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
13 actionable tasks: 13 executed
java -server -XX:+AggressiveOpts -Xms2g -Xmx2g -jar build\libs\app.jar deser --apis stream --libs genson jackson
**Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [jackson]
        at io.airlift.airline.Cli.validate(Cli.java:194)
        at io.airlift.airline.Cli.parse(Cli.java:132)
        at io.airlift.airline.Cli.parse(Cli.java:108)
        at io.airlift.airline.Cli.parse(Cli.java:103)
        at com.github.fabienrenaud.jjb.Cli.main(Cli.java:40)**

$> ./run ser --apis databind,stream --libs jackson**
.\gradlew clean build shadowJar

> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileTestJava
Note: C:\Users\lange\dev\projects\external-workspaces\java-json-benchmark\src\test\java\com\github\fabienrenaud\jjb\JsonBenchmark.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

com.github.fabienrenaud.jjb.data.gen.ClientsGeneratorTest > populateClientCollection_1k STANDARD_OUT
    Using SEED=793328287 as seed for Random

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
13 actionable tasks: 13 executed
java -server -XX:+AggressiveOpts -Xms2g -Xmx2g -jar build\libs\app.jar ser --apis databind stream --libs jackson
**Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [stream]
        at io.airlift.airline.Cli.validate(Cli.java:194)
        at io.airlift.airline.Cli.parse(Cli.java:132)
        at io.airlift.airline.Cli.parse(Cli.java:108)
        at io.airlift.airline.Cli.parse(Cli.java:103)
        at com.github.fabienrenaud.jjb.Cli.main(Cli.java:40)**

**$> ./run deser --apis stream --libs dsljson,jackson --size 10 --datatype users**
.\gradlew clean build shadowJar

> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileTestJava
Note: C:\Users\lange\dev\projects\external-workspaces\java-json-benchmark\src\test\java\com\github\fabienrenaud\jjb\JsonBenchmark.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

com.github.fabienrenaud.jjb.data.gen.ClientsGeneratorTest > populateClientCollection_1k STANDARD_OUT
    Using SEED=793328287 as seed for Random

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
13 actionable tasks: 13 executed
java -server -XX:+AggressiveOpts -Xms2g -Xmx2g -jar build\libs\app.jar deser --apis stream --libs dsljson jackson --size 10 --datatype users
**Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [jackson]
        at io.airlift.airline.Cli.validate(Cli.java:194)
        at io.airlift.airline.Cli.parse(Cli.java:132)
        at io.airlift.airline.Cli.parse(Cli.java:108)
        at io.airlift.airline.Cli.parse(Cli.java:103)
        at com.github.fabienrenaud.jjb.Cli.main(Cli.java:40)**

**Environment**: Window 10 and OpenJDK Runtime Environment (Zulu 8.56.0.23-CA-win64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.23-CA-win64) (build 25.302-b08, mixed mode).

**Comment by fabienrenaud** [comment]
Commands work fine on Mac and Linux and I don't have a Windows machine to test. Feel free to propose a fix, or close.

**Comment by langelescu** [comment]
The issue seems to be a difference in the parsing of the command line arguments in Windows terminal/console. I will look more into this when I have a chance. I can confirm it runs fine in Linux, but not necessarily in WSL 2. I encountered some issues there, will verify later.
