### ISSUE TITLE
Redundant initialization of JsonObjectBuilder compromises the results for javaxjson

### ISSUE THREAD

**Issue by langelescu** [fabienrenaud/java-json-benchmark#42]
The streaming serialization benchmark for javaxjson does not yield accurate results. The culprit is the redundant initialization of the JsonObjectBuilder in the UsersStreamSerialization.java. Removing the unneeded objects improves performance across the board, with improvements of more than 30x for small payloads. 

Check pull request #41

**Comment by fabienrenaud** [comment]
@langelescu Indeed! Thank you for catching that and submitting a PR to fix it. I've merge the PR.
I'll try to find some time in the near future to re-run the full benchmark to get updated results. In the mean time, I'll leave this issue opened and will close it when the new benchmarks are published.

**Comment by fabienrenaud** [comment]
A new benchmark was published in April 2023. Closing this.
