### ISSUE TITLE
Different dataset for each fork

### ISSUE THREAD

**Issue by meylism** [fabienrenaud/java-json-benchmark#46]
Hi @fabienrenaud,

May I ask the reasoning behind using different (randomly generated) dataset for each fork? Doesn't it result in a run-to-run variance?

Thanks,
Meylis

**Comment by fabienrenaud** [comment]
It would if the system was using a true random number generator, but like most systems, it uses a pseudo-random number generator initialized by a seed. For a given seed, the sequence of numbers returned by the RNG is deterministic. 
The same SEED value is used across entire test suites, so although the data is regenerated for each input variant, the generated bytes are the same.
The SEED value can also be set via environment variable in you case you want to execute `./run` several times in a row...
