### ISSUE TITLE
Q: Any plans for bumping java-json-benchmark to use Java 11 / support libraries that target Java 11+ ?

### ISSUE THREAD

**Issue by rbygrave** [fabienrenaud/java-json-benchmark#47]
Are there plans to bump java-json-benchmark to Java 11?

The impact is that I would like to change the avaje-jsonb library to target Java 11. If I do that then it won't run in this benchmark project as it uses java 8. Is there any reason for java-json-benchmark to stay with Java 8?  Should I submit a PR to bump it to 11?

**Comment by fabienrenaud** [comment]
> The impact is that I would like to change the avaje-jsonb library to target Java 11.

Unless you are actually planning to use Java >8 features _for good reasons_ in your lib, I would recommend against this. Many popular Java frameworks still build java8 compatible jars (or even older versions) to maximize compatibility and encourage adoption.

> Should I submit a PR to bump it to 11?

You may.
If you do so, please also provide ser+deser results for several of the most popular libs in your PR. If switching to Java 11 somehow results in significant relative changes in performance, more work may be needed to support benchmarking against multiple runtime versions.

**Comment by rbygrave** [comment]
> Unless you are actually planning to use Java >8 features for good reasons in your lib, I would recommend against this.

Well yes it is a tricky one.  For my oldest and most popular library Ebean ORM I asked the question 6 months ago - 
https://github.com/ebean-orm/ebean/issues/2374 ... there are some users / projects that are still locked into Java 8 but at the same time that number _seems_ small and those projects locked into Java 8 are also the projects that are generally not updating libraries or adopting new ones. Hard to say though as 95% of library users don't actively participate in these types of discussions/decisions.

For my newer libraries there are people wanting to use jlink and for those people slf4j-api is somewhat a problem at the moment - so `System.Logger` becomes an option for Java 9+ and my newer libraries will bump to Java 11 and often change to `System.Logger` (good for people wanting to use jlink). It might be different story if slf4j-api 2.x becomes non-alpha. In terms of module-info I have been using moditect-maven-plugin and multi-release jars which is ok but I have noticed that this allows errors in module-info to go undetected over time. The process of adding module-info to my older/larger libraries has uncovered some less desirable things that needed to be addressed and I think using an always enforced module-info will produce better long term health for these libraries.

For the case of avaje-jsonb it is hard to say - it has pretty close to zero adoption at the moment :) ... how many likely adopters are locked into Java 8?  I suspect very few, I suspect adopters will be Java 11+. 

That all said, I could be wrong and people jump up and down for Java 8 support.


> If you do so, please also provide ser+deser results for several of the most popular libs in your PR

Ok cool, will do.

**Comment by rbygrave** [comment]
Closing with PR - https://github.com/fabienrenaud/java-json-benchmark/pull/48 ...
