### ISSUE TITLE
Build crashing?

### ISSUE THREAD

**Issue by a2800276** [fabienrenaud/java-json-benchmark#5]
I've been trying to get the benchmarks to run (JDK1.8) but the entire run never gets passed the compileJars task, gradle crashes hard, resulting in a `hs_err_pid....log` which indicates the crash takes place in `Java Thread "Daemon worker"`

I'm basically just starting the benchmark with the `bench` script with `./bench ser` but started digging into the individual gradle tasks step by step.

I'm still not convinced that this is not the result of me doing something obviously stupid, but the same crash takes place on OSX (javac 1.8.0_101) and on Ubunutu (javac 1.8.0_121) and I'm a bit stumped... 

Attached is an OSX crash file in case that helps.

[hs_err_pid78626.log.zip](https://github.com/fabienrenaud/java-json-benchmark/files/799446/hs_err_pid78626.log.zip)

**Comment by fabienrenaud** [comment]
I was able to repro.
For some reason the project doesn't build with gradle 3.3 and 3.2.1 (didn't try other versions).
I downgraded the gradlew version to 2.14.1 and it builds again.

I pushed the fix.
https://github.com/fabienrenaud/java-json-benchmark/commit/ad4421fd9a7fbfc8128468c00cf899db4e5ceda1

**Comment by a2800276** [comment]
Oh the horror. 🥇 Thanks for spotting this and responding so quickly.

**Comment by fabienrenaud** [comment]
Will follow up with gradle: https://discuss.gradle.org/t/crash-with-gradle-build-v3/21742
