### ISSUE TITLE
Is it possible to launch bench on Mac?

### ISSUE THREAD

**Issue by anton-fedorov** [fabienrenaud/java-json-benchmark#8]
Hi,

I'm having following output, when running `bench` or `bench-all`:

```$ ./bench ser --apis databind,stream --libs dsljson
error: Mono is required to run DSL compiler. Mono not detected or specified.
error: DSL compilation error
  Unable to setup DSL-JSON processing environment. Specify dsljson.loglevel=DEBUG for more information.
2 errors

FAILURE: Build failed with an exception.
```

Is it possible to launch dsljson benchmark on mac?

**Comment by fabienrenaud** [comment]
Yes, I run my benchmark on Mac.

As indicated by the error message, you need to install mono because of dsl-platform json lib.
```brew install mono``` should do it.
